name: 🐛 Bug Report
description: Report a bug or issue with Platform Coach/Lifter
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix the issue.

  - type: dropdown
    id: app-version
    attributes:
      label: Which app are you using?
      description: Select the version you're experiencing issues with
      options:
        - Platform Coach (Paid - platformcoach.app)
        - Platform Lifter (Free - platformlifter.app)
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Which tool were you using?
      description: Select the feature where the bug occurred
      options:
        - Competition Planner - Pro Mode
        - Competition Planner - Lite Mode
        - Game Day Mode
        - Workout Timer
        - 1RM & Training Load Calculator
        - Warm-up Generator
        - Velocity Profile Generator
        - Technique Score Calculator
        - Export/Import (PDF, CSV, .plp files)
        - Settings/Branding
        - Other/General
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely
      placeholder: "Example: When I try to export my competition plan to PDF, nothing downloads and I see an error in the console."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen instead
      placeholder: "Example: I expected a PDF file to download with my complete competition plan."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce this bug
      placeholder: |
        1. Go to Competition Planner
        2. Create a new plan with attempts
        3. Click 'Export to PDF'
        4. See error...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "e.g., Windows 11, macOS 14, iOS 17, Android 14"

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      description: Can you reproduce this bug consistently?
      options:
        - Every time
        - Sometimes
        - Only once
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: |
        - Were you online or offline?
        - Had you just imported a plan?
        - Any browser extensions that might interfere?
        - Console error messages (F12 → Console tab)

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
