name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input.

  - type: dropdown
    id: app-version
    attributes:
      label: Which app is this for?
      options:
        - Platform Coach (Paid)
        - Platform Lifter (Free)
        - Both
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: "Example: I'm always frustrated when I have to manually calculate my attempt jumps for different strategies..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
      placeholder: "Example: Add a feature that lets me compare different attempt strategies side-by-side before committing to one..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Alternative solutions or features you've considered
      placeholder: "Example: I currently create multiple plans and compare them manually, but this is time-consuming..."

  - type: dropdown
    id: tool
    attributes:
      label: Which feature area does this relate to?
      options:
        - Competition Planner
        - Game Day Mode
        - Workout Timer
        - 1RM Calculator
        - Warm-up Generator
        - Velocity Profile Tools
        - Technique Score Calculator
        - Export/Import Features
        - Settings/Configuration
        - New Tool (not listed above)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request
